import { describe, expect, it } from "vitest";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { analyzeAgentConfigDamage } from "./agent_config_damage.js";

function tmpProject(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "anamnesis-agent-damage-"));
}

function writeFile(project: string, relPath: string, text: string): void {
  const absPath = path.join(project, relPath);
  fs.mkdirSync(path.dirname(absPath), { recursive: true });
  fs.writeFileSync(absPath, text, "utf8");
}

describe("agent config damage diagnostics", () => {
  it("detects hand-authored bootstrap ontology files in nested scopes", () => {
    const project = tmpProject();
    writeFile(
      project,
      "apps/api/.anamnesis/ontology/api.bootstrap.yaml",
      'schema_version: "anamnesis.bootstrap.v1"\n',
    );
    writeFile(
      project,
      "packages/web/.anamnesis/ontology/web.bootstrap.yaml",
      "# AUTO-GENERATED by anamnesis ontology bootstrap\nschema_version: \"anamnesis.bootstrap.v1\"\n",
    );
    writeFile(
      project,
      "node_modules/pkg/.anamnesis/ontology/pkg.bootstrap.yaml",
      'schema_version: "anamnesis.bootstrap.v1"\n',
    );

    const status = analyzeAgentConfigDamage({ projectRoot: project });

    expect(status.issues.map((issue) => issue.target)).toEqual([
      "apps/api/.anamnesis/ontology/api.bootstrap.yaml",
    ]);
    expect(status.issues[0]?.code).toBe("bootstrap-ontology-hand-edited");
  });

  it("does not treat fenced handoff examples as startup archive injection", () => {
    const project = tmpProject();
    writeFile(
      project,
      "AGENTS.md",
      [
        "Use this handoff template:",
        "```markdown",
        "# Handoff - Example",
        "## Goal",
        "## Done so far",
        "## In flight",
        "## Decisions",
        "## Open questions / blockers",
        "## Next steps",
        "```",
        "",
      ].join("\n"),
    );

    const status = analyzeAgentConfigDamage({ projectRoot: project });

    expect(status.ok).toBe(true);
    expect(status.issues).toEqual([]);
  });
});
