// Shared renderer for deterministic Layer A ontology bootstrap files.

import { stringify as stringifyYaml } from "yaml";
import type { Introspector } from "./introspector.js";

const VERSION = "0.5.0";

export function renderBootstrapOntology(
  introspector: Introspector,
  facts: object,
): string {
  const yaml = stringifyYaml(facts, {
    sortMapEntries: true,
    aliasDuplicateObjects: false,
  });
  return `${buildBootstrapHeader(introspector)}${yaml}`;
}

function buildBootstrapHeader(introspector: Introspector): string {
  return [
    `# AUTO-GENERATED by 'anamnesis ontology bootstrap' — do not edit by hand.`,
    `# Re-run bootstrap to refresh. To add semantic notes, edit`,
    `# .anamnesis/ontology/${introspector.fragmentId}.enriched.yaml instead.`,
    `#`,
    `# generator: anamnesis@${VERSION} introspector=${introspector.fragmentId}`,
    ``,
  ].join("\n");
}
