import * as fs from "node:fs";
import * as path from "node:path";
import type { RenderAction } from "./render.js";

export type ProjectDocsMode = "scaffold" | "enhance";

export type ProjectDocsTargetOutcome =
  | "planned-create"
  | "planned-enhance"
  | "skipped-existing";

export interface ProjectDocsTarget {
  path: string;
  outcome: ProjectDocsTargetOutcome;
  reason: string;
}

export interface ProjectDocsPlan {
  mode: ProjectDocsMode;
  actions: RenderAction[];
  targets: ProjectDocsTarget[];
}

const PROJECT_DOCS_FRAGMENT_ID = "project-docs";
const PROJECT_DOCS_FRAGMENT_VERSION = 1;
const PROJECT_CONTEXT_DOC_PATH = "docs/PROJECT-CONTEXT.md";

export function planProjectDocs(opts: {
  projectRoot: string;
  projectName: string;
  scaffoldDocs: boolean;
  enhanceDocs: boolean;
}): ProjectDocsPlan | undefined {
  if (!opts.scaffoldDocs && !opts.enhanceDocs) return undefined;

  const mode: ProjectDocsMode = opts.enhanceDocs ? "enhance" : "scaffold";
  const description = readPackageDescription(opts.projectRoot);
  const targets: ProjectDocsTarget[] = [];
  const actions: RenderAction[] = [];

  const readme = planDocTarget({
    projectRoot: opts.projectRoot,
    path: "README.md",
    mode,
    regionId: "anamnesis-readme-context",
    content: readmeRegionContent({
      projectName: opts.projectName,
      description,
      existing: fs.existsSync(path.join(opts.projectRoot, "README.md")),
    }),
  });
  targets.push(readme.target);
  actions.push(...readme.actions);

  const contextDoc = planDocTarget({
    projectRoot: opts.projectRoot,
    path: PROJECT_CONTEXT_DOC_PATH,
    mode,
    regionId: "anamnesis-project-context",
    content: projectContextRegionContent({
      projectName: opts.projectName,
      existing: fs.existsSync(
        path.join(opts.projectRoot, "docs", "PROJECT-CONTEXT.md"),
      ),
    }),
  });
  targets.push(contextDoc.target);
  actions.push(...contextDoc.actions);

  return { mode, actions, targets };
}

function planDocTarget(input: {
  projectRoot: string;
  path: string;
  mode: ProjectDocsMode;
  regionId: string;
  content: string;
}): { target: ProjectDocsTarget; actions: RenderAction[] } {
  const exists = fs.existsSync(path.join(input.projectRoot, input.path));
  if (input.mode === "scaffold" && exists) {
    return {
      target: {
        path: input.path,
        outcome: "skipped-existing",
        reason:
          "existing user-authored document left untouched; use --enhance-docs to add the managed review section",
      },
      actions: [],
    };
  }

  return {
    target: {
      path: input.path,
      outcome: exists ? "planned-enhance" : "planned-create",
      reason: exists
        ? "managed anamnesis region will be added or refreshed without replacing user-authored content"
        : "missing project document will be created with an anamnesis-managed starter region",
    },
    actions: [
      {
        kind: "region",
        file: input.path,
        regionId: input.regionId,
        fragmentId: PROJECT_DOCS_FRAGMENT_ID,
        fragmentVersion: PROJECT_DOCS_FRAGMENT_VERSION,
        content: input.content,
      },
    ],
  };
}

function readmeRegionContent(input: {
  projectName: string;
  description?: string;
  existing: boolean;
}): string {
  const title = input.existing ? "## AI Agent Context" : `# ${input.projectName}`;
  const intro = input.existing
    ? "This section gives Claude Code, Codex, Cursor, and other agents the stable context entrypoints they should read before changing code."
    : (input.description ??
      "Project documentation scaffold generated by anamnesis. Replace this sentence with the human-facing product overview when the project purpose is settled.");

  return `${title}

${intro}

## Context Sources

- Canonical agent entrypoint: \`AGENTS.md\`
- Claude Code pointer surface: \`CLAUDE.md\` when the Claude adapter is installed
- Project-level ontology: \`system_graph.yaml\`
- Generated ontology slices: \`.anamnesis/ontology/*.yaml\`
- Semantic enrichment path: run \`/ontology-enrich\` after the project has enough intent, architecture, or operational constraints to record
- Handoff path: run \`/handoff-prepare\` before switching agents with in-progress work

## Review Checklist

- Fill in the project purpose, user-facing workflow, setup commands, and operating constraints outside this managed region.
- Move durable architecture facts or invariants into \`system_graph.yaml\` or \`docs/PROJECT-CONTEXT.md\`.
- Keep secrets, private customer names, tokens, and infrastructure credentials out of public documentation.
`;
}

function projectContextRegionContent(input: {
  projectName: string;
  existing: boolean;
}): string {
  const title = input.existing
    ? "## Anamnesis Context Review"
    : `# Project Context - ${input.projectName}`;

  return `${title}

This document is a project-facing context scaffold. It is intentionally factual and conservative: record only information that future agents can safely rely on.

## What To Capture

- Purpose: what the project does and who it serves
- Entrypoints: commands, services, jobs, or UI routes agents should inspect first
- Architecture: key modules, external systems, data stores, and call paths
- Operations: deploy, migration, release, rollback, and incident constraints
- Invariants: things agents must always or never do

## Anamnesis Sources

- \`AGENTS.md\` carries cross-agent working instructions.
- \`CLAUDE.md\`, \`.codex/\`, and \`.cursor/\` carry adapter-specific surfaces when installed.
- \`system_graph.yaml\` is the user-managed top-level ontology.
- \`.anamnesis/ontology/*.bootstrap.yaml\` is deterministic Layer A output.
- \`.anamnesis/ontology/*.enriched.yaml\` is agent-reviewed Layer B semantic context.
`;
}

function readPackageDescription(projectRoot: string): string | undefined {
  const filepath = path.join(projectRoot, "package.json");
  if (!fs.existsSync(filepath)) return undefined;
  try {
    const parsed = JSON.parse(fs.readFileSync(filepath, "utf8")) as {
      description?: unknown;
    };
    return typeof parsed.description === "string" ? parsed.description : undefined;
  } catch {
    return undefined;
  }
}
