// `anamnesis ontology bootstrap` — Layer A of the hybrid ontology
// bootstrap (see docs/ONTOLOGY-BOOTSTRAP.md).
//
// Walks the project's installed fragments, looks up a registered
// introspector for each, runs it, and writes the result to
// `.anamnesis/ontology/<fragment-id>.bootstrap.yaml`.
//
// v0.4.0 first cut: root scope only. Multi-scope bootstrap is a
// follow-up — same code path, just iterate `effectiveScopes` instead
// of treating the project as one root.

import * as fs from "node:fs";
import * as path from "node:path";
import { stringify as stringifyYaml } from "yaml";
import { findAgentfile, readAgentfile } from "../core/agentfile.js";
import { effectiveScopes } from "../core/scope.js";
import {
  IntrospectorRegistry,
  type Introspector,
} from "../core/introspector.js";
import { makeBuiltinIntrospectorRegistry } from "../introspectors/index.js";
import { ProjectContext } from "../core/triggers.js";

const VERSION = "0.4.0";

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

export class OntologyBootstrapError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "OntologyBootstrapError";
  }
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type BootstrapOutcome =
  | "written"
  | "unchanged"
  | "skipped-not-applicable"
  | "skipped-no-introspector";

export interface BootstrapEntry {
  /** Scope path from Agentfile. Root scope is ".". */
  scopePath: string;
  fragmentId: string;
  outcome: BootstrapOutcome;
  /** Relative path to the produced file (only when outcome === "written" / "unchanged"). */
  path?: string;
}

export interface BootstrapResult {
  projectRoot: string;
  entries: BootstrapEntry[];
  writtenToDisk: boolean;
}

export interface BootstrapOptions {
  projectRoot: string;
  /** Only run this fragment's introspector. Default: all installed fragments. */
  fragment?: string;
  /** Print plan, no writes. */
  dryRun?: boolean;
  /** Override the introspector registry (tests). */
  registry?: IntrospectorRegistry;
}

// ---------------------------------------------------------------------------
// Output formatting
// ---------------------------------------------------------------------------

function buildHeader(introspector: Introspector): string {
  return [
    `# AUTO-GENERATED by 'anamnesis ontology bootstrap' — do not edit by hand.`,
    `# Re-run bootstrap to refresh. To add semantic notes, edit`,
    `# .anamnesis/ontology/${introspector.fragmentId}.enriched.yaml instead.`,
    `#`,
    `# generator: anamnesis@${VERSION} introspector=${introspector.fragmentId}`,
    ``,
  ].join("\n");
}

function serialize(introspector: Introspector, facts: object): string {
  const yaml = stringifyYaml(facts, {
    sortMapEntries: true,
    aliasDuplicateObjects: false,
  });
  return `${buildHeader(introspector)}${yaml}`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

export function bootstrap(opts: BootstrapOptions): BootstrapResult {
  const projectRoot = path.resolve(opts.projectRoot);
  const apply = opts.dryRun !== true;

  if (!findAgentfile(projectRoot)) {
    throw new OntologyBootstrapError(
      `no Agentfile found at ${projectRoot} — run 'anamnesis init' first`,
    );
  }
  const agentfile = readAgentfile(projectRoot);

  const registry = opts.registry ?? makeBuiltinIntrospectorRegistry();
  const scopes = effectiveScopes(agentfile);
  const selectedScopes = scopes.map((scope) => ({
    scope,
    fragments: opts.fragment
      ? scope.fragments.filter((f) => f.id === opts.fragment)
      : scope.fragments,
  }));
  const installedInAnyScope = selectedScopes.some((s) => s.fragments.length > 0);

  if (opts.fragment && !installedInAnyScope) {
    throw new OntologyBootstrapError(
      `fragment '${opts.fragment}' is not installed in this project`,
    );
  }

  const entries: BootstrapEntry[] = [];
  let anyWritten = false;

  for (const { scope, fragments } of selectedScopes) {
    const scopeRoot =
      scope.path === "." || scope.path === ""
        ? projectRoot
        : path.join(projectRoot, scope.path);
    const ctx = new ProjectContext(scopeRoot);
    const ontologyDir = path.join(scopeRoot, ".anamnesis", "ontology");

    for (const installed of fragments) {
      const introspector = registry.for(installed.id);
      if (!introspector) {
        entries.push({
          scopePath: scope.path,
          fragmentId: installed.id,
          outcome: "skipped-no-introspector",
        });
        continue;
      }
      if (!introspector.appliesTo(ctx)) {
        entries.push({
          scopePath: scope.path,
          fragmentId: installed.id,
          outcome: "skipped-not-applicable",
        });
        continue;
      }
      const facts = introspector.introspect(ctx);
      const content = serialize(introspector, facts);
      const scopeRel =
        scope.path === "." || scope.path === "" ? "" : scope.path;
      const relPath = path.posix.join(
        scopeRel,
        ".anamnesis",
        "ontology",
        `${introspector.fragmentId}.bootstrap.yaml`,
      );
      const absPath = path.join(projectRoot, relPath);
      const existing = fs.existsSync(absPath)
        ? fs.readFileSync(absPath, "utf8")
        : null;
      const unchanged = existing === content;
      if (apply && !unchanged) {
        fs.mkdirSync(ontologyDir, { recursive: true });
        fs.writeFileSync(absPath, content, "utf8");
        anyWritten = true;
      }
      entries.push({
        scopePath: scope.path,
        fragmentId: installed.id,
        outcome: unchanged ? "unchanged" : "written",
        path: relPath,
      });
    }
  }

  return {
    projectRoot,
    entries,
    writtenToDisk: apply && anyWritten,
  };
}
